[package]
name = "clam"
version = "0.4.0"
edition = "2024"
authors = ["Maarten van Gompel <proycon@anaproy.nl>"]
description = "Quickly build RESTful webservices and user interfaces around your command-line tools"
include = ["src/**/*","tests/**/*", "LICENSE", "README.md"]
license = "AGPL-3.0-only"
readme = "README.md"
repository = "https://github.com/proycon/clam"
keywords = [ "webservice", "rest"]

[dependencies]
axum = { version = "0.8.8", features = ["multipart"] }
axum-extra = { version = "0.12.6", features = ["cookie"] }
base64 = "0.22.1"
clap = { version = "4.5.60", features = ["derive"] }
const_format = "0.2.36"
derive-getters = { version = "0.5.0", features = ["auto_copy_getters"] }
futures-util = "0.3.32"
jsonwebtoken = { version = "10.4.0", features = ["rust_crypto"] }
md5 = "0.8.0"
nix = { version = "0.31.3", features = ["signal"]}
rand = "0.10.1"
regex = "1.13.0"
reqwest = { version = "0.13.4", features = ["blocking", "form", "json"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
tokio = { version = "1.52.0", features = ["signal", "macros", "rt-multi-thread", "fs"] }
tokio-util = { version = "0.7.18", features = [ "io" ]}
toml = "1.1.2"
tower-http = { version = "0.6.8", features = ["trace", "normalize-path"] }
tracing = "0.1.44"
tracing-subscriber = "0.3.23"
upon = "0.11.0"
utoipa = { version = "5.5.0", features = ["axum_extras"] }
utoipa-swagger-ui = { version = "9.0.2", features = ["axum", "vendored"] }
