[service]
name = "freqlist"
description = "This webservice produces a frequency list for an input file"
rootdir = "./data"
command = "./freqlist.sh"

[service.auth]
postauth_url = "/index"

[service.license]
name = "GNU Affero General Public License"
id = "AGPL-3.0-only"
url = "https://www.gnu.org/licenses/agpl-3.0.en.html"

[[service.args]]
parameter_id = "casesensitive"

[[service.args]]
parameter_id = "tokinput"

[[service.filetypes]]
id = "plaintext"
name = "Plain Text (UTF-8)"
contenttype = "text/plain; charset=utf-8"

[[service.endpoints]]
path = "/"
mode = "Porch"

#Index of endpoints and projects
[[service.endpoints]]
path = "/index"
mode = "Index"

[[service.endpoints]]
path = "/"  #project name will be appended automatically
mode = "Project"
status_pattern = ".*" #every line from stderr qualifies as a status message

[[service.endpoints.parameters]]
id = "tokinput"
description = "Tokenised text input"
required = true
type = { parametertype = "File", filetype = "plaintext", name = { nametype = "Pattern", value = "*.txt" } }

[[service.endpoints.parameters]]
id = "casesensitive"
description = "Case sensitivity"
required = false
type = { parametertype = "Boolean", default = false, flag = "-c"  }
