name = "freqlist"
summary = "This webservice produces a frequency list for an input file"
description = "You can upload a plain text file, and the tokens in it will be analysed and their frequency outputted in a TSV file"
rootdir = "./data"
version = "0.1"

[auth]
postauth_url = "/index"

[license]
name = "GNU Affero General Public License"
id = "AGPL-3.0-only"
url = "https://www.gnu.org/licenses/agpl-3.0.en.html"

[contact]
name = "Maarten van Gompel"
url = "https://proycon.anaproy.nl"
email = "proycon@anaproy.nl"


[[filetypes]]
id = "plaintext"
name = "Plain Text (UTF-8)"
contenttype = "text/plain; charset=utf-8"

[[filetypes]]
id = "tsv"
name = "Tab Separated Values (UTF-8)"
contenttype = "text/tsv"

[[endpoints]]
path = "/"
mode = "LandingPage"

#Index of endpoints and projects
[[endpoints]]
path = "/index"
mode = "Index"

[[endpoints]]
path = "/"  #project name will be appended automatically
mode = "Project"
status_pattern = ".*" #every line from stderr qualifies as a status message
command = "freqlist.sh"

[[endpoints.args]]
parameter_id = "casesensitive"

[[endpoints.args]]
parameter_id = "tokinput"

[[endpoints.parameters]]
id = "tokinput"
name = "Input text"
description = "Input text to process, must be tokenised already (spaces separating tokens)"
required = true
type = { parametertype = "File", filetype = "plaintext", filename = { nametype = "Pattern", value = "\\.txt$" } }

[[endpoints.parameters]]
id = "casesensitive"
name = "Case sensitivity"
description = "Treat items that differ in case as distinct?"
required = false
type = { parametertype = "Bool", default = false, flag = "-c"  }

[[outputfiles]]
name = "Frequency list"
type = "tsv"
filename = { nametype = "Pattern", value = "*.txt" }
